#!/usr/bin/env python3
"""Write the VDCR V2 draft status report from draft samples and manifest rows."""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from datetime import date
from pathlib import Path
from typing import Any


DOMAINS = [
    "biology_living_systems",
    "chemistry_materials_change",
    "earth_environmental_systems",
    "physics_physical_systems",
]


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def expansion_axis_rows(manifest_rows: list[dict[str, str]]) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    seed_answers = {row.get("answer", "") for row in manifest_rows if row.get("review_status") == "v2_seed"}
    seen_answers = set(seed_answers)
    concept_axis: list[dict[str, str]] = []
    video_axis: list[dict[str, str]] = []
    for row in manifest_rows:
        if row.get("review_status") == "v2_seed":
            continue
        answer = row.get("answer", "")
        if answer and answer not in seen_answers:
            concept_axis.append(row)
            seen_answers.add(answer)
        else:
            video_axis.append(row)
    return concept_axis, video_axis


def cluster_distribution(samples: list[dict[str, Any]]) -> Counter[int]:
    answer_counts = Counter(str(row.get("answer", "")) for row in samples if row.get("answer"))
    return Counter(answer_counts.values())


def markdown_list(values: list[str], empty: str = "none") -> str:
    unique_values = [value for value in dict.fromkeys(values) if value]
    if not unique_values:
        return empty
    return ", ".join(f"`{value}`" for value in unique_values)


def build_report(
    samples: list[dict[str, Any]],
    manifest_rows: list[dict[str, str]],
    *,
    report_date: date,
    target_samples: int,
    target_unique_min: int,
    target_unique_max: int,
    max_videos_per_concept: int,
) -> str:
    answer_counts = Counter(str(row.get("answer", "")) for row in samples if row.get("answer"))
    domain_counts = Counter(str(row.get("domain", "")) for row in samples)
    seed_rows = [row for row in manifest_rows if row.get("review_status") == "v2_seed"]
    appended_rows = [row for row in manifest_rows if row.get("review_status") != "v2_seed"]
    concept_axis, video_axis = expansion_axis_rows(manifest_rows)
    cluster_counts = cluster_distribution(samples)
    repeated_answers = [(answer, count) for answer, count in answer_counts.most_common() if count > 1]

    lines = [
        "# VDCR V2 Draft Status",
        "",
        f"Date: {report_date.isoformat()}",
        "",
        "Generated by `scripts/build_vdcr_v2_draft_status.py`.",
        "",
        "## Current Draft",
        "",
        "- `data/vdcr_v2_draft_samples.jsonl`: source-hidden V2 draft dataset.",
        "- `data/vdcr_v2_draft_manifest.csv`: internal provenance manifest for seed and appended V2 draft rows.",
        "",
        "Current draft contents:",
        "",
        f"- total samples: {len(samples)} / target {target_samples} (remaining {max(target_samples - len(samples), 0)})",
        f"- V1 seed samples: {len(seed_rows)}",
        f"- appended V2 pass-candidate samples: {len(appended_rows)}",
        f"- unique concepts/answers: {len(answer_counts)} / target {target_unique_min}-{target_unique_max}",
        f"- max videos per concept cluster: {max(answer_counts.values(), default=0)} / cap {max_videos_per_concept}",
        f"- repeated concept clusters: {sum(count > 1 for count in answer_counts.values())}",
        f"- clusters with 1 video: {cluster_counts.get(1, 0)}",
        f"- clusters with 2 videos: {cluster_counts.get(2, 0)}",
        f"- clusters with 3 videos: {cluster_counts.get(3, 0)}",
        "",
        "## Expansion Axes",
        "",
        "V2 expands along two separate axes:",
        "",
        f"- concept-axis additions: {len(concept_axis)} samples introduce concepts not present in the V1 seed draft.",
        f"- video-axis additions: {len(video_axis)} samples add another strongly bound video to an existing concept cluster.",
        "",
        f"Concept-axis additions: {markdown_list([row.get('answer', '') for row in concept_axis])}.",
        "",
        f"Video-axis additions: {markdown_list([row.get('answer', '') for row in video_axis])}.",
        "",
        "Repeated concept clusters:",
        "",
        "| Concept | Videos |",
        "|---|---:|",
    ]
    for answer, count in repeated_answers:
        lines.append(f"| `{answer}` | {count} |")
    if not repeated_answers:
        lines.append("| none | 0 |")

    lines.extend(
        [
            "",
            "## Domain Distribution",
            "",
            "| Domain | Samples |",
            "|---|---:|",
        ]
    )
    for domain in DOMAINS:
        lines.append(f"| `{domain}` | {domain_counts.get(domain, 0)} |")

    lines.extend(
        [
            "",
            "## Appended V2 Draft Rows",
            "",
            "| Video ID | Candidate | Concept | Axis | Domain |",
            "|---|---|---|---|---|",
        ]
    )
    concept_ids = {id(row) for row in concept_axis}
    for row in appended_rows:
        axis = "concept" if id(row) in concept_ids else "video"
        lines.append(
            "| `{video_id}` | `{candidate}` | `{answer}` | `{axis}` | `{domain}` |".format(
                video_id=row.get("video_id", ""),
                candidate=row.get("candidate_id", ""),
                answer=row.get("answer", ""),
                axis=axis,
                domain=row.get("domain", ""),
            )
        )

    lines.extend(
        [
            "",
            "## Validation",
            "",
            "Schema/source-hidden validation:",
            "",
            "```bash",
            "python3 scripts/validate_vdcr_direct_answer.py \\",
            "  --input data/vdcr_v2_draft_samples.jsonl \\",
            "  --release-mode \\",
            f"  --min-samples {len(samples)} \\",
            "  --allow-duplicate-answers \\",
            f"  --max-videos-per-answer {max_videos_per_concept}",
            "```",
            "",
            f"This validates {len(samples)} rows. Full `--check-media` currently depends on restoring the ignored V1 media cache.",
            "",
            "## Next Gap",
            "",
            "The draft is not yet the final V2 benchmark. The shortest path to the first target is to keep adding strict concept-axis rows in the smallest domains, then fill high-confidence concept clusters toward the 3-video cap where the repeated videos show meaningfully different visual evidence.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--samples", type=Path, default=Path("data/vdcr_v2_draft_samples.jsonl"))
    parser.add_argument("--manifest", type=Path, default=Path("data/vdcr_v2_draft_manifest.csv"))
    parser.add_argument("--output", type=Path, default=Path("reports/vdcr_v2_draft_status.md"))
    parser.add_argument("--target-samples", type=int, default=300)
    parser.add_argument("--target-unique-min", type=int, default=200)
    parser.add_argument("--target-unique-max", type=int, default=220)
    parser.add_argument("--max-videos-per-concept", type=int, default=3)
    args = parser.parse_args()

    report = build_report(
        read_jsonl(args.samples),
        read_csv(args.manifest),
        report_date=date.today(),
        target_samples=args.target_samples,
        target_unique_min=args.target_unique_min,
        target_unique_max=args.target_unique_max,
        max_videos_per_concept=args.max_videos_per_concept,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
