#!/usr/bin/env python3
"""Build a local-media triage sheet for VDCR V2 candidate review."""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path


TRIAGE_FIELDS = [
    "candidate_id",
    "candidate_knowledge_point",
    "concept_id",
    "domain_seed",
    "subdomain_seed",
    "source_platform",
    "source_url",
    "license_or_usage_note",
    "local_media",
    "contact_sheet",
    "suggested_start_sec",
    "suggested_end_sec",
    "repeat_concept_rank",
    "repeat_concept_cap",
    "triage_status",
    "visual_gate_focus",
    "reviewer_decision",
    "reviewer_notes",
]


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, str]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        writer.writerows([{field: row.get(field, "") for field in fields} for row in rows])


def build_triage_rows(review_rows: list[dict[str, str]]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for row in review_rows:
        if not row.get("local_media") or not row.get("contact_sheet"):
            continue
        rows.append(
            {
                "candidate_id": row.get("candidate_id") or row.get("id", ""),
                "candidate_knowledge_point": row.get("candidate_knowledge_point", ""),
                "concept_id": row.get("concept_id", ""),
                "domain_seed": row.get("domain_seed", ""),
                "subdomain_seed": row.get("subdomain_seed", ""),
                "source_platform": row.get("source_platform", ""),
                "source_url": row.get("source_url", ""),
                "license_or_usage_note": row.get("license_or_usage_note", ""),
                "local_media": row.get("local_media", ""),
                "contact_sheet": row.get("contact_sheet", ""),
                "suggested_start_sec": row.get("suggested_start_sec", ""),
                "suggested_end_sec": row.get("suggested_end_sec", ""),
                "repeat_concept_rank": row.get("repeat_concept_rank", ""),
                "repeat_concept_cap": row.get("repeat_concept_cap", ""),
                "triage_status": "ready_for_manual_review",
                "visual_gate_focus": row.get("review_notes", ""),
                "reviewer_decision": "",
                "reviewer_notes": "",
            }
        )
    rows.sort(key=lambda item: (item["domain_seed"], item["candidate_knowledge_point"], item["candidate_id"]))
    return rows


def write_report(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    by_domain = Counter(row["domain_seed"] for row in rows)
    by_concept = Counter(row["candidate_knowledge_point"] for row in rows)
    lines = [
        "# VDCR V2 Local Review Triage",
        "",
        "Generated by `scripts/build_vdcr_v2_review_triage.py`.",
        "",
        "This report lists V2 candidates that already have local media and sparse contact sheets.",
        "They are reviewable candidates, not accepted samples.",
        "",
        "## Summary",
        "",
        f"- local-review candidates: {len(rows)}",
        f"- unique concepts: {len(by_concept)}",
        "",
        "## Domain Counts",
        "",
        "| Domain | Rows |",
        "|---|---:|",
    ]
    for domain, count in sorted(by_domain.items()):
        lines.append(f"| `{domain}` | {count} |")
    lines.extend(
        [
            "",
            "## Candidate Rows",
            "",
            "| Candidate | Concept | Domain | Media | Contact sheet |",
            "|---|---|---|---|---|",
        ]
    )
    for row in rows:
        lines.append(
            "| `{candidate_id}` | `{concept}` | `{domain}` | `{media}` | `{sheet}` |".format(
                candidate_id=row["candidate_id"],
                concept=row["candidate_knowledge_point"],
                domain=row["domain_seed"],
                media=row["local_media"],
                sheet=row["contact_sheet"],
            )
        )
    lines.extend(
        [
            "",
            "## Manual Review Decisions",
            "",
            "Fill `reviewer_decision` in `data/vdcr_v2_local_review_triage.csv` with one of:",
            "",
            "- `pass_candidate`: video independently satisfies dynamic, leakage, shortcut, and license gates.",
            "- `revise`: useful source, but needs trimming, muting, answer-leak removal, or tighter concept binding.",
            "- `reject`: concept is not visually grounded, too broad, duplicated, leaky, or source/licensing is unsuitable.",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--review-queue", type=Path, default=Path("data/vdcr_v2_review_queue.csv"))
    parser.add_argument("--output", type=Path, default=Path("data/vdcr_v2_local_review_triage.csv"))
    parser.add_argument("--report", type=Path, default=Path("reports/vdcr_v2_local_review_triage.md"))
    args = parser.parse_args()

    rows = build_triage_rows(read_csv(args.review_queue))
    write_csv(args.output, rows, TRIAGE_FIELDS)
    write_report(args.report, rows)
    print(f"triage_rows={len(rows)} wrote {args.output}")
    print(f"wrote {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
