#!/usr/bin/env python3
"""Build the V2 concept inventory from the tiered V1 pool plus V2 expansion rows."""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows([{field: row.get(field, "") for field in fieldnames} for row in rows])


def normalized_answer(row: dict[str, str]) -> str:
    return (row.get("recommended_answer_en") or row.get("concept_en") or "").casefold().strip()


def merge_concepts(base_rows: list[dict[str, str]], expansion_rows: list[dict[str, str]]) -> list[dict[str, str]]:
    if not base_rows:
        return expansion_rows
    fieldnames = list(base_rows[0].keys())
    base_ids = {row.get("concept_id", "") for row in base_rows}
    base_answers = {normalized_answer(row) for row in base_rows if normalized_answer(row)}

    merged = list(base_rows)
    for row in expansion_rows:
        concept_id = row.get("concept_id", "")
        answer = normalized_answer(row)
        if not concept_id:
            raise ValueError("V2 expansion row is missing concept_id")
        if concept_id in base_ids:
            raise ValueError(f"duplicate concept_id in V2 expansion: {concept_id}")
        if answer in base_answers:
            raise ValueError(f"duplicate recommended answer in V2 expansion: {row.get('recommended_answer_en')}")
        merged.append({field: row.get(field, "") for field in fieldnames})
        base_ids.add(concept_id)
        base_answers.add(answer)
    return merged


def write_report(path: Path, rows: list[dict[str, str]], base_count: int, expansion_count: int) -> None:
    main_tiers = {"core_main", "strict_main_candidate"}
    tier_counts = Counter(row.get("concept_validity_tier", "") for row in rows)
    domain_counts = Counter(row.get("domain", "") for row in rows)
    main_domain_counts = Counter(
        row.get("domain", "") for row in rows if row.get("concept_validity_tier", "") in main_tiers
    )

    lines = [
        "# VDCR V2 Concept Inventory",
        "",
        "Generated by `scripts/build_vdcr_v2_concept_inventory.py`.",
        "",
        "This inventory keeps the tiered V1 concept pool intact and appends V2-only concepts for scaling.",
        "",
        "## Summary",
        "",
        f"- base concepts: {base_count}",
        f"- V2 expansion concepts: {expansion_count}",
        f"- total concepts: {len(rows)}",
        f"- main-eligible concepts: {sum(tier_counts.get(tier, 0) for tier in main_tiers)}",
        "",
        "## Tier Counts",
        "",
        "| Tier | Concepts |",
        "|---|---:|",
    ]
    for tier, count in sorted(tier_counts.items()):
        lines.append(f"| `{tier}` | {count} |")
    lines.extend(["", "## Main-Eligible Domain Counts", "", "| Domain | Main-eligible concepts | Total concepts |", "|---|---:|---:|"])
    for domain in sorted(domain_counts):
        lines.append(f"| `{domain}` | {main_domain_counts.get(domain, 0)} | {domain_counts.get(domain, 0)} |")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", type=Path, default=Path("data/vdcr_concept_inventory_tiered_v1.csv"))
    parser.add_argument("--expansion", type=Path, default=Path("data/vdcr_v2_concept_expansion.csv"))
    parser.add_argument("--output", type=Path, default=Path("data/vdcr_v2_concept_inventory.csv"))
    parser.add_argument("--report", type=Path, default=Path("reports/vdcr_v2_concept_inventory.md"))
    args = parser.parse_args()

    base_rows = read_csv(args.base)
    expansion_rows = read_csv(args.expansion)
    merged = merge_concepts(base_rows, expansion_rows)
    write_csv(args.output, merged, list(base_rows[0].keys()))
    write_report(args.report, merged, len(base_rows), len(expansion_rows))
    print(f"base_concepts={len(base_rows)}")
    print(f"expansion_concepts={len(expansion_rows)}")
    print(f"merged_concepts={len(merged)} wrote {args.output}")
    print(f"wrote {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
